version = "2"
generators = ["go"]

# defaults are "/usr/local/include" and "/usr/include", which don't exist on Windows.
# override defaults to supress errors about non-existant directories.
after = []

[[overrides]]
prefixes = [
    "ttrpc-stress/runner/payload_protogogo",
]
generators = ["gogo"]
