// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ttrpc-stress/runner/payload_protogogo/type.proto

package payload_protogogo

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Payload struct {
	Value                uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7513ecaac1c3ca, []int{0}
}
func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Payload)(nil), "type.Payload")
}

func init() {
	proto.RegisterFile("ttrpc-stress/runner/payload_protogogo/type.proto", fileDescriptor_df7513ecaac1c3ca)
}

var fileDescriptor_df7513ecaac1c3ca = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x28, 0x29, 0x29, 0x2a,
	0x48, 0xd6, 0x2d, 0x2e, 0x29, 0x4a, 0x2d, 0x2e, 0xd6, 0x2f, 0x2a, 0xcd, 0xcb, 0x4b, 0x2d, 0xd2,
	0x2f, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0x89, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xcf, 0x4f,
	0xcf, 0xd7, 0x2f, 0xa9, 0x2c, 0x48, 0xd5, 0x03, 0x73, 0x85, 0x58, 0x40, 0x6c, 0x25, 0x79, 0x2e,
	0xf6, 0x00, 0x88, 0x2a, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xde, 0x20, 0x08, 0xc7, 0x49, 0x3d, 0x4a, 0x95, 0x28, 0xa3, 0x93, 0xd8, 0xc0, 0x4c,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x19, 0x0a, 0xd4, 0x8a, 0x00, 0x00, 0x00,
}
